spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:file:./db/course_work
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
logging:
  file:
    name: log.log